version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm
    versioning-strategy: auto
    groups:
      dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 10
    rebase-strategy: auto
    reviewers:
      - UgolinOlle
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
